In [27]:
from sklearn.feature_extraction.text import CountVectorizer
from nltk.tokenize import sent_tokenize
import numpy as np 

text = 'This is the first document. This document is the second document. And this is the third one. Is this the first document?'
corpus = sent_tokenize(text)

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names())
print(X.toarray())  

['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']
[[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]


In [28]:
print(corpus)

['This is the first document.', 'This document is the second document.', 'And this is the third one.', 'Is this the first document?']


In [29]:
import csv
with open('train.tsv') as f:
    reader = csv.reader(f)
    your_list = list(reader)

print(your_list[:3])

[['PhraseId\tSentenceId\tPhrase\tSentiment'], ['1\t1\tA series of escapades demonstrating the adage that what is good for the goose is also good for the gander ', ' some of which occasionally amuses but none of which amounts to much of a story .\t1'], ['2\t1\tA series of escapades demonstrating the adage that what is good for the goose\t2']]


In [30]:
##
import pandas as pd
df=pd.read_csv('train.tsv', sep='\t')
df.iloc[:,3]
df.head() 

PhraseId  SentenceId                                             Phrase  \
0         1           1  A series of escapades demonstrating the adage ...   
1         2           1  A series of escapades demonstrating the adage ...   
2         3           1                                           A series   
3         4           1                                                  A   
4         5           1                                             series   

   Sentiment  
0          1  
1          2  
2          2  
3          2  
4          2

In [45]:
corpus = df['Phrase']
sentval = df['Sentiment']
y = np.zeros(len(sentval))
y[sentval > 2] = 1
print(sum(y))

42133.0


In [43]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
print(X.toarray())  

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [38]:
print(np.sum(X,0))

[[ 23 179  70 ...  15   9   5]]


In [39]:
print(X.shape)

(156060, 15240)


In [57]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import RandomOverSampler


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=42)
ros = RandomOverSampler(random_state=0)
X_resampled, y_resampled = ros.fit_resample(X_train, y_train)

clf = LogisticRegression(random_state=0, solver='lbfgs').fit(X_resampled, y_resampled)

accuracy = clf.score(X_test, y_test)

print("test-set",accuracy)
print("train-set",clf.score(X_train,y_train))


test-set 0.8350890683070614
train-set 0.8768935024990389


/Users/alexanderjung/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
